'use client'
import { generateClient } from 'aws-amplify/api'
import { defaultItinerary, type Itinerary } from './types'
import { v4 as uuidv4 } from 'uuid'

const client = generateClient()

// GraphQL operations (normally auto-generated by Amplify, inlined here)
const listItineraries = /* GraphQL */ `
  query ListItineraries {
    listItineraries {
      items {
        id owner sharedWith shareToken shareLinkEnabled data
      }
    }
  }
`
const createItinerary = /* GraphQL */ `
  mutation CreateItinerary($input: CreateItineraryInput!) {
    createItinerary(input: $input) { id owner sharedWith shareToken shareLinkEnabled data }
  }
`
const updateItinerary = /* GraphQL */ `
  mutation UpdateItinerary($input: UpdateItineraryInput!) {
    updateItinerary(input: $input) { id owner sharedWith shareToken shareLinkEnabled data }
  }
`
const onUpdateItinerary = /* GraphQL */ `
  subscription OnUpdateItinerary($id: ID!) {
    onUpdateItinerary(filter: { id: { eq: $id } }) { id data }
  }
`
const getItineraryByToken = /* GraphQL */ `
  query GetItineraryByToken($shareToken: String!) {
    listItineraries(filter: { shareToken: { eq: $shareToken }, shareLinkEnabled: { eq: true } }) {
      items { id owner sharedWith shareToken shareLinkEnabled data }
    }
  }
`

let cachedItineraryId: string | null = null

export async function loadItinerary(): Promise<{ id: string; itinerary: Itinerary; sharedWith: string[]; shareToken: string | null; shareLinkEnabled: boolean }> {
  const result = await client.graphql({ query: listItineraries }) as any
  const items = result.data?.listItineraries?.items ?? []
  if (items.length === 0) {
    const created = await client.graphql({
      query: createItinerary,
      variables: { input: { data: JSON.stringify(defaultItinerary()), sharedWith: [], shareLinkEnabled: false } },
    }) as any
    const item = created.data.createItinerary
    cachedItineraryId = item.id
    return { id: item.id, itinerary: defaultItinerary(), sharedWith: [], shareToken: null, shareLinkEnabled: false }
  }
  const item = items[0]
  cachedItineraryId = item.id
  return {
    id: item.id,
    itinerary: JSON.parse(item.data) as Itinerary,
    sharedWith: item.sharedWith ?? [],
    shareToken: item.shareToken ?? null,
    shareLinkEnabled: item.shareLinkEnabled ?? false,
  }
}

export async function saveItinerary(id: string, data: Itinerary) {
  await client.graphql({
    query: updateItinerary,
    variables: { input: { id, data: JSON.stringify(data) } },
  })
}

export function subscribeToItinerary(id: string, onUpdate: (data: Itinerary) => void) {
  const sub = (client.graphql({ query: onUpdateItinerary, variables: { id } }) as any).subscribe({
    next: ({ data }: any) => {
      const updated = data?.onUpdateItinerary
      if (updated) onUpdate(JSON.parse(updated.data) as Itinerary)
    },
  })
  return () => sub.unsubscribe()
}

export async function inviteByEmail(itineraryId: string, email: string, currentSharedWith: string[]) {
  // In production this would call a Lambda to look up the Cognito user sub by email.
  // Here we store the email directly as an identifier.
  const updated = [...new Set([...currentSharedWith, email])]
  await client.graphql({
    query: updateItinerary,
    variables: { input: { id: itineraryId, sharedWith: updated } },
  })
  return updated
}

export async function removeCollaborator(itineraryId: string, email: string, currentSharedWith: string[]) {
  const updated = currentSharedWith.filter(e => e !== email)
  await client.graphql({
    query: updateItinerary,
    variables: { input: { id: itineraryId, sharedWith: updated } },
  })
  return updated
}

export async function generateShareLink(itineraryId: string): Promise<string> {
  const token = uuidv4()
  await client.graphql({
    query: updateItinerary,
    variables: { input: { id: itineraryId, shareToken: token, shareLinkEnabled: true } },
  })
  return `${window.location.origin}/join/${token}`
}

export async function revokeShareLink(itineraryId: string) {
  await client.graphql({
    query: updateItinerary,
    variables: { input: { id: itineraryId, shareLinkEnabled: false, shareToken: null } },
  })
}

export async function joinByToken(token: string): Promise<string | null> {
  const result = await client.graphql({ query: getItineraryByToken, variables: { shareToken: token } }) as any
  const items = result.data?.listItineraries?.items ?? []
  if (items.length === 0) return null
  return items[0].id
}
